import os


ECONOMY_V1_ENABLED = os.getenv("ECONOMY_V1_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE2_ENABLED = os.getenv("ECONOMY_PHASE2_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE3_ENABLED = os.getenv("ECONOMY_PHASE3_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE4_ENABLED = os.getenv("ECONOMY_PHASE4_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE5_ENABLED = os.getenv("ECONOMY_PHASE5_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE6_ENABLED = os.getenv("ECONOMY_PHASE6_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE7_ENABLED = os.getenv("ECONOMY_PHASE7_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_PHASE8_ENABLED = os.getenv("ECONOMY_PHASE8_ENABLED", "false").strip().lower() in {
    "1", "true", "yes", "on"
}
ECONOMY_BACKUP_DIR = os.getenv("ECONOMY_BACKUP_DIR", "./backups/economy")
ECONOMY_REPORT_DIR = os.getenv("ECONOMY_REPORT_DIR", "./reports/economy")
ECONOMY_MAX_AMOUNT = int(os.getenv("ECONOMY_MAX_AMOUNT", "9000000000000000"))
ECONOMY_CONFIRM_TIMEOUT_SECONDS = int(os.getenv("ECONOMY_CONFIRM_TIMEOUT_SECONDS", "120"))
ECONOMY_MIGRATION_VERSION = 100
ECONOMY_PHASE2_MIGRATION_VERSION = 200
ECONOMY_PHASE3_MIGRATION_VERSION = 300
ECONOMY_PHASE4_MIGRATION_VERSION = 400
ECONOMY_PHASE5_MIGRATION_VERSION = 500
ECONOMY_PHASE6_MIGRATION_VERSION = 600
ECONOMY_PHASE7_MIGRATION_VERSION = 700
ECONOMY_PHASE8_MIGRATION_VERSION = 800
LEGACY_SCALE = 1_000
ASSET_UNIT_SCALE = 100_000_000

CURRENCIES = ("ETM", "ECY")

RPG_MAX_LEVEL = 100
RPG_DEFAULT_MAX_HP = 1_000
RPG_DEFAULT_ATTACK = 50
RPG_DEFAULT_DEFENSE = 25
RPG_DEFAULT_CRIT_BPS = 500
RPG_MAX_CRIT_BPS = 5_000
RPG_MAX_ENERGY = 100
RPG_ENERGY_REGEN_SECONDS = 10 * 60

RPG_PHASE3_CATALOG_VERSION = "rpg-v1.0.0"
RPG_MAX_PET_LEVEL = 50
RPG_CRITICAL_MULTIPLIER_BPS = 15_000
RPG_MAX_DAMAGE_REDUCTION_BPS = 6_000
RPG_BOSS_ATTACK_COOLDOWN_SECONDS = 30

DAILY_REWARD_ETM = 50_000
DAILY_REWARD_ECY = 5_000
WEEKLY_REWARD_ETM = 350_000
WEEKLY_REWARD_ECY = 35_000
WORK_REWARD_MIN_ETM = 10_000
WORK_REWARD_MAX_ETM = 18_000
WORK_COOLDOWN_SECONDS = 2 * 60 * 60
WORK_DAILY_LIMIT = 4
WORK_ROLL_STALE_SECONDS = 24 * 60 * 60
TRANSFER_MIN_ETM = 10_000
TRANSFER_DAILY_LIMIT_ETM = 2_000_000
ECONOMY_FEE_BPS = 500

SYSTEM_ACCOUNT_DEFINITIONS = {
    "ETM_GENERAL": ("ETM", "TREASURY", 1, 0),
    "ETM_BOSS_DUNGEON": ("ETM", "TREASURY", 1, 0),
    "ETM_EVENT": ("ETM", "TREASURY", 1, 0),
    "ETM_RESERVE": ("ETM", "RESERVE", 0, 0),
    "ETM_BURN": ("ETM", "BURN", 0, 0),
    "ETM_ISSUANCE": ("ETM", "ISSUANCE", 0, 1),
    "ECY_GENERAL": ("ECY", "TREASURY", 1, 0),
    "ECY_GIVEAWAY": ("ECY", "TREASURY", 1, 0),
    "ECY_CASINO": ("ECY", "TREASURY", 1, 0),
    "ECY_MARKET": ("ECY", "TREASURY", 1, 0),
    "ECY_MINING": ("ECY", "TREASURY", 1, 0),
    "ECY_RESERVE": ("ECY", "RESERVE", 0, 0),
    "ECY_BURN": ("ECY", "BURN", 0, 0),
    "ECY_ISSUANCE": ("ECY", "ISSUANCE", 0, 1),
}

EMERGENCY_FEATURES = (
    "economy", "casino", "crypto", "exchange", "giveaway", "options", "mining", "marketplace"
)

MARKETPLACE_MIN_PRICE_ETM = 10_000
MARKETPLACE_MAX_PRICE_ETM = 2_000_000_000
MARKETPLACE_MAX_UNRESOLVED_LISTINGS = 10
MARKETPLACE_MAX_WATCHES = 50
MARKETPLACE_REPORT_COOLDOWN_SECONDS = 60 * 60
MARKETPLACE_FEE_BPS = 500
SQLITE_MAX_INTEGER = 9_223_372_036_854_775_807

CASINO_WAGER_STEP_ECY = 1_000
CASINO_MIN_WAGER_ECY = 1_000
CASINO_MAX_WAGER_ECY = 500_000
CASINO_EXPOSURE_BPS = 200
CASINO_MAX_UNRESOLVED_GUILD = 100
CASINO_CONFIRM_TIMEOUT_SECONDS = 90
CASINO_BLACKJACK_ABANDON_SECONDS = 10 * 60
CASINO_AUTH_CLASSES = ("CASINO_CONTROL", "CASINO_FINANCIAL", "CASINO_RECOVERY")

CRYPTO_FEE_BPS = 200
CRYPTO_MIN_GROSS_ECY = 50
CRYPTO_MEAN_REVERSION_BPS = 200
CRYPTO_NORMAL_EVENT_PER_100000 = 50
CRYPTO_MAJOR_EVENT_PER_100000 = 5
CRYPTO_NEWS_COOLDOWN_SECONDS = 30 * 60
CRYPTO_ASSETS = {
    "ETHR": ("ETHERnal", 10_000, 15, "LOW"),
    "ORCL": ("Cosmic Oracle", 10_000, 25, "LOW"),
    "MTR": ("Meteorite", 10_000, 35, "MODERATE"),
    "ECLP": ("Eclipsoin", 10_000, 50, "MODERATE"),
    "ORBT": ("Orbitcoin", 20_000, 70, "HIGH"),
    "TRST": ("TrustCoin", 14_000, 90, "HIGH"),
    "LUNA": ("Lunniera", 13_000, 120, "EXTREME"),
}

MINING_RIG_CATALOG = {
    "rig_basic": ("Basic Rig", 500_000, 10_000, 2_500),
    "rig_advanced": ("Advanced Rig", 3_000_000, 60_000, 15_000),
    "rig_elite": ("Elite Rig", 15_000_000, 300_000, 75_000),
    "rig_eternal": ("Eternal Rig", 75_000_000, 1_500_000, 375_000),
}
MINING_AUTH_CLASSES = ("MINING_CONTROL", "MINING_RECOVERY")

GIVEAWAY_TICKET_ECY = 10_000
GIVEAWAY_ACTIVITY_MINIMUM = 80
GIVEAWAY_CLAIM_SECONDS = 24 * 60 * 60
OPTIONS_MIN_STAKE_ECY = 1_000
OPTIONS_MAX_STAKE_ECY = 500_000
OPTIONS_STAKE_STEP_ECY = 1_000
OPTIONS_GROSS_PAYOUT_BPS = 19_000
OPTIONS_MAX_ACTIVE = 3
OPTIONS_DURATIONS_MINUTES = (5, 10, 30)

SEED_ENVIRONMENTS = {
    "ETM_GENERAL": "ECONOMY_SEED_ETM_GENERAL",
    "ETM_BOSS_DUNGEON": "ECONOMY_SEED_ETM_BOSS_DUNGEON",
    "ETM_EVENT": "ECONOMY_SEED_ETM_EVENT",
    "ECY_GENERAL": "ECONOMY_SEED_ECY_GENERAL",
    "ECY_GIVEAWAY": "ECONOMY_SEED_ECY_GIVEAWAY",
    "ECY_CASINO": "ECONOMY_SEED_ECY_CASINO",
    "ECY_MARKET": "ECONOMY_SEED_ECY_MARKET",
    "ECY_MINING": "ECONOMY_SEED_ECY_MINING",
}


def configured_whitelist_ids():
    values = []
    for raw in os.getenv("ECONOMY_MINT_WHITELIST", "").split(","):
        value = raw.strip()
        if value.isdigit() and int(value) > 0:
            values.append(value)
    return tuple(dict.fromkeys(values))


def configured_large_threshold(action, currency):
    key = f"ECONOMY_LARGE_{str(action).upper()}_{str(currency).upper()}"
    raw = os.getenv(key, "").strip()
    if not raw.isdigit() or int(raw) <= 0:
        return None
    return int(raw)
